# Generated by Django 3.2.4 on 2021-06-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_remove_formation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
