# Generated by Django 3.2.4 on 2021-06-12 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='categorie',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='formation.categorie'),
        ),
    ]
