# Generated by Django 3.2.4 on 2021-06-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_formation_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
